### ISSUE TITLE
Consume the SDK dependency from the dep-server

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core-sdk#223]
Per https://github.com/paketo-buildpacks/dep-server/issues/45, we should start consuming the .NET Core SDK dependency from the dep-server (https://api.deps.paketo.io/v1/dependency?name=dotnet-sdk and https://deps.paketo.io/dotnet-sdk/...) instead of the https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/... location we currently get the dependencies from.

This will make the dependency publishing/consumption process more transparent than the process we use for the dependencies available via the [dependency-builds pipeline](https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds).

We have already done this switch-over in the Node Engine and Yarn Buildpacks. The outline of what this work will entail can be found in the dep-server issue linked at the top.

**Comment by fg-j** [comment]
The dep server automation doesn't currently have any way of updating the compatibility table in the buildpack toml. Automation will need to be added that updates the compatibility table when the versions of the SDK are updated.

**Comment by sophiewigmore** [comment]
Looking into creating an action to do the compatibility table updates.
