### ISSUE TITLE
Implement RFC 0006

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/dotnet-core-sdk#415]
## Describe the Enhancement

[.NET Core RFC 0006](https://github.com/paketo-buildpacks/rfcs/blob/ccfbcb20e4643d9883998ae47ae7a37c92aa3f90/text/dotnet-core/0005-simplify-runtime-dependency.md) has been approved and merged.

## Possible Solution

 - [x] This buildpack no longer need to move the `dotnet` cli into a `.dotnet_root` directory.
 - [x] This buildpack no longer needs to set the `.dotnet_root` on the path using an environment layer.

## Motivation

 This is part of https://github.com/paketo-buildpacks/dotnet-core/issues/755.

**Comment by fg-j** [comment]
We should ensure that this is done in a way that is backward compatible with the existing dotnet-core-runtime and dotnet-core-aspnet buildpacks.
