### ISSUE TITLE
Restructure: Only provide the dotnet-sdk dependency

### ISSUE THREAD

**Issue by joshzarrabi** [paketo-buildpacks/dotnet-core-sdk#94]
### Background

This buildpack currently provides the `dotnet-sdk` dependency, which 
* Installs a version of the SDK onto the `$DOTNET_ROOT`
* Installs a version of the Dotnet Core Driver on the `$PATH`

It always requires itself, `dotnet-core-runtime` and `dontet-core-aspnet` on both `launch` and `build`.

### Proposal

In order to conform the the [restructure rfc](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0001-restructure.md), this buildpack should provide the `dotnet-sdk` dependency and require nothing. This will greatly simplify its interaction with other buildpacks in the language family.

The buildpack should Install a specified version of the SDK onto the `$DOTNET_ROOT`
The buildpack should install a specified version of the Dotnet Core Driver on the `$PATH`
The buildpack should also be rewritten in a `packit` compliant way.

**Comment by ForestEckhardt** [comment]
Some quick notes:
- `detect` should always provide `dotnet-sdk` and require it if there is an entry in `buildpack.yml`.
- The current logic in `build` should be simplified to mimic that of our other provision buildpacks. We should priority sort, find a compatible version (if one exists), and install that version. Leave the failure to `dotnet-publish` or when the container is run.

Priority Order:
1. `buildpack.yml`
1. `global.json`
1. `*.*sproj`

**Comment by fg-j** [comment]
`build` should look for the `RUNTIME_VERSION` env var set by the `dotnet-runtime` buildpack and use this to determine the SDK to install. It should check whether this version is compatible with the one listed in the `global.json`, and if not, fail to build.

**Comment by fg-j** [comment]
If `RUNTIME_VERSION` is not set, use the above stated priority order to determine a runtime version to install **without** SDK version roll forward logic.
